version: 2

jobs:
  build_and_test:
    docker:
      - image: docker:18.06.1-ce-git
    working_directory: ~/CircleCI/docker-airflow
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: 
          name: Build docker image
          command: |
            docker build -t russ0519/docker-airflow-2.7 .
      - run: 
          name: Test docker image
          command: |
            docker run russ0519/docker-airflow-2.7 version |grep '1.10.2'
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
